# Generated by Django 4.2.1 on 2023-05-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=8, unique=True)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Select Gender', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=13)),
                ('level', models.IntegerField(choices=[('Select Level', 'Select Level'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])),
                ('status', models.CharField(choices=[('Select Status', 'Select Status'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=13)),
                ('department', models.CharField(choices=[('Select Dept', 'Select Dept'), ('General', 'General'), ('Computer Science', 'Computer Science'), ('Information Systems', 'Information Systems'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Information Technology', 'Information Technology'), ('Data Scince', 'Data Scince'), ('CyberSecurity', 'CyberSecurity'), ('BioInformatics', 'BioInformatics'), ('Decision Support', 'Decision Support'), ('Scientific Computing', 'Scientific Computing')], max_length=23)),
            ],
        ),
    ]
